language: c
dist: bionic
os:
  - linux
compiler:
  - clang
  - gcc
arch:
  - amd64
env:
  global:
    - MAKEFLAGS="-j$(nproc)"
matrix:

install:
  - ci/travis-install.sh

script:
  - ci/travis-build.sh
